// src/lib/exerciseDb.js
// Search index loader for the exercises dataset.
//
// Source: https://github.com/hasaneyldrm/exercises-dataset (1,324 exercises)
// Runtime payload: public/exercises-index.json — a slim projection generated by
// scripts/build-exercise-index.mjs. The upstream data/exercises.json is ~17.5 MB
// because every record carries instructions in 10 languages; we only need identity,
// searchable labels, and an image path.
//
// Images are still-only and served from the raw CDN. Note the filename is
// "{id}-{media_id}.jpg" and is NOT derivable from the id, so every image URL comes
// from the record's own `image` field rather than being constructed.

const IMAGE_BASE = 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/refs/heads/main'

/** Turns a dataset `image` path ("images/0289-SpYC0Kp.jpg") into a CDN URL. */
export function imageUrl(imagePath) {
  if (!imagePath) return null
  return `${IMAGE_BASE}/${imagePath}`
}

let _cache = null
let _inflight = null

export async function loadExerciseIndex() {
  if (_cache) return _cache
  if (!_inflight) {
    const base = import.meta.env.BASE_URL || '/'
    _inflight = fetch(`${base}exercises-index.json`)
      .then(res => {
        if (!res.ok) throw new Error(`Exercise index failed to load (${res.status})`)
        return res.json()
      })
      .then(data => {
        _cache = data
        return data
      })
      .finally(() => {
        _inflight = null
      })
  }
  return _inflight
}

/**
 * Scores a record against a lowercase query. Returns -1 for no match.
 * Prefix matches on the name rank highest so "bench" surfaces "bench press"
 * above "bench press on a stability ball".
 */
function score(ex, q) {
  const name = ex.name.toLowerCase()
  if (name.startsWith(q)) return 0
  if (name.includes(q)) return 1
  if (ex.target?.toLowerCase().includes(q)) return 2
  if (ex.body_part?.toLowerCase().includes(q)) return 3
  if (ex.equipment?.toLowerCase().includes(q)) return 4
  return -1
}

const RESULT_LIMIT = 60

/**
 * Searches the index. With no query and no filters, returns a representative
 * first slice rather than all 1,324 records.
 */
export async function searchExercises(query, { bodyPart = '', equipment = '' } = {}) {
  const all = await loadExerciseIndex()
  const q = query.trim().toLowerCase()

  let pool = all
  if (bodyPart) pool = pool.filter(ex => ex.body_part === bodyPart)
  if (equipment) pool = pool.filter(ex => ex.equipment === equipment)

  if (!q) return pool.slice(0, RESULT_LIMIT)

  const hits = []
  for (const ex of pool) {
    const rank = score(ex, q)
    if (rank >= 0) hits.push({ ex, rank })
  }
  hits.sort((a, b) => a.rank - b.rank || a.ex.name.localeCompare(b.ex.name))
  return hits.slice(0, RESULT_LIMIT).map(h => h.ex)
}

/** Distinct values for the filter chips, derived from the loaded index. */
export async function getExerciseFacets() {
  const all = await loadExerciseIndex()
  const bodyParts = [...new Set(all.map(e => e.body_part))].sort()
  const equipment = [...new Set(all.map(e => e.equipment))].sort()
  return { bodyParts, equipment }
}

/**
 * Image paths for the 10 pre-loaded exercises, verified against the dataset.
 * These are the only records whose image URL cannot be read from the index at
 * render time, because the Log screen needs them before the index is fetched.
 */
export const DEFAULT_EXERCISE_IMAGE_MAP = {
  '1': 'images/0289-SpYC0Kp.jpg', // Dumbbell Flat Bench → dumbbell bench press
  '2': 'images/0314-ns0SIbU.jpg', // Incline Dumbbell Press → dumbbell incline bench press
  '3': 'images/0405-znQUdHY.jpg', // Shoulder Press → dumbbell seated shoulder press
  '4': 'images/2330-LEprlgG.jpg', // Lat Pull Down → cable lat pulldown full range of motion
  '5': 'images/0160-veXwo0D.jpg', // Close Grip Row → cable floor seated wide-grip row
  '6': 'images/0159-kesXOpB.jpg', // Wide Grip Row → cable decline seated wide-grip row
  '7': 'images/0178-goJ6ezq.jpg', // Cable Lateral Raise → cable lateral raise
  '8': 'images/0173-Hx1WC8I.jpg', // Tricep Extension → cable incline triceps extension
  '9': 'images/1634-otqIxU4.jpg', // Bicep Curl → cable lying bicep curl
  '10': 'images/0165-HPlPoQA.jpg', // Hammer Curl → cable hammer curl (with rope)
}
